-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "slotEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "slotIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "slotStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Schedule" ADD COLUMN     "slotDuration" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "totalSlots" INTEGER NOT NULL DEFAULT 1;
